# Generated by Django 3.1.4 on 2020-12-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201215_0827'),
        ('todo_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='listmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listmodel'),
        ),
    ]
